packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - argon2
  - '@tailwindcss/oxide'
  - lightningcss

supportedArchitectures:
  os: [current, linux, darwin]
  cpu: [current, x64, arm64]
  libc: [current, glibc]
