import { zhCN } from '@vital/tokens';

/** Web UI is zh-CN. Shared keys live in @vital/tokens; screen copy stays here until i18n grows. */
export const t = {
  brand: zhCN.brand,
  nav: {
    ...zhCN.nav,
    library: '资料库',
    logout: '退出登录',
    quickAdd: '新建',
    palette: '命令面板',
    searchHint: '搜索 ⌘K',
  },
  lists: zhCN.lists,
  reports: {
    ...zhCN.reports,
    kicker: '把完成的事留下痕迹。',
    fill: '从本周期填充',
    filling: '填充中…',
    source: '源码',
    wysiwyg: '排版',
    sourceToggle: '切换源码',
    journal: '这一天',
    remoteUpdated: '远端已更新',
    conflict: '报告已被更新，请先同步',
    reload: '重新加载',
    keepLocal: '保留本地',
    saving: '保存中…',
    saved: '已保存',
    unsaved: '未保存',
    pinTask: '插入任务',
    pinInbox: '插入稍后读',
    slashHint: '插入任务或稍后读',
    slashEmpty: '输入关键词搜索任务或稍后读',
    deleted: '已删除',
    retry: '重试',
    loading: '加载中',
    history: '往期',
    period: '周期',
    periodStats: '周期统计',
    streakHint: '格子深浅是完成多少，小点是写下的日子。点一天打开。',
    wrote: '写下',
    completed: '完成',
    carried: '结转',
    captured: '收集',
    emptyDone: '还没有完成。做完一件，会记在这里。',
    emptyCarried: '没有要结转的事。',
    finishedLater: '后来完成',
    emptyCaptured: '这一期没有新的稍后读。',
    streakCompleted: '连续完成 {n} 天',
    streakWrote: '连续写下 {n} 天',
    pinToNotes: '钉进写下',
    body: '报告正文',
    title: '标题',
    chipTask: '任务',
    chipInbox: '稍后读',
    complete: '完成',
    bold: '粗体',
    italic: '斜体',
    strike: '删除线',
    heading: '一级标题',
    heading2: '小标题',
    quote: '引用',
    bullet: '列表',
    ordered: '编号列表',
    code: '代码块',
    link: '链接',
    image: '图片',
    attach: '附件',
    table: '表格',
    rule: '分割线',
    linkPrompt: '链接地址',
    uploadFailed: '上传失败，请换一张图或一个文件再试。',
  },
  rail: {
    rhythm: '待办',
    capture: '收集',
    reflect: '复盘',
    lists: '清单',
    todos: '待办',
    collapse: '收起侧栏',
    expand: '展开侧栏',
    resize: '拖动调整列宽',
  },
  theme: {
    label: '主题',
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
    switch: '切换深色模式',
  },
  auth: {
    loginKicker: '夜色收好，白天接着做。',
    registerKicker: '先把一件事放进来。',
    loginTitle: '登录 Vital',
    registerTitle: '加入 Vital',
    email: '邮箱',
    password: '密码',
    displayName: '怎么称呼你',
    confirmPassword: '再输一遍密码',
    loginSubmit: '登录',
    registerSubmit: '注册',
    loggingIn: '登录中…',
    registering: '注册中…',
    noAccount: '还没有账号？',
    hasAccount: '已有账号？',
    passwordMismatch: '两次密码不一致',
    invalidEmail: '请输入正确的邮箱地址',
    passwordMin: '密码至少 8 位',
    passwordRequired: '请输入密码',
    displayNameRequired: '请输入名字',
    extensionTitle: '连接浏览器扩展',
    extensionKicker: '登录后把扩展接到这个账号。',
    extensionConnecting: '正在连接扩展…',
    extensionConnected: '已连接到扩展',
    extensionConnectedHint: '可以关闭此页，回到刚才的标签保存。',
    extensionMissingId: '请从 Vital 扩展打开此页。',
    extensionFailed: '扩展没有响应',
    extensionNoRuntime: '当前浏览器无法连接扩展',
  },
  empty: {
    today: '今天还没有安排，也没有逾期。按 N 新建。',
    inboxList: '收集箱是空的。',
    upcoming: '这里还没有任务。',
    done: '完成的任务会出现在这里。',
    userList: '把任务拖进来，或按 N。',
    board: '还没有卡片。',
    calendar: '这一周没有日期。',
    inbox: '把稍后读的页先丢进来。',
    inboxTitle: '把值得重读的东西，先安静地放在这里。',
    inboxHint: '看到好文章不必马上读完。存进收集箱，它会在你准备好的时候等你。',
    inboxKbd: '微信 / 扩展 / 手机均可收集',
    inboxReader: '打开一条稍后再读。',
    reports: '写今天的日报，把完成的事留下痕迹。',
    reportEditor: '今天想留下一句就够。',
    search: '输入关键词搜任务、稍后读和报告。',
    library: '标签和模板会集中在这里。',
    settings: '这是你的空间。称呼、提醒、外观和模型都在这里。',
    onboarding: '先建一条任务，或把一页收进稍后读。',
    notFound: '没有这个页面。',
    tags: '还没有标签。',
    actionNew: '新建',
    actionExtension: '安装扩展',
    actionDaily: '打开今日日报',
    actionHome: '回到今天',
    searchNone: '没有匹配的任务、稍后读或报告。',
  },
  onboarding: {
    skip: '跳过',
    skipAll: '跳过引导',
    next: '下一步',
    start: '开始使用',
    stepOf: '第 {n} 步，共 3 步',
    steps: [
      {
        title: '把一页收进来',
        body: '稍后读是口袋。粘贴链接，或用扩展保存当前页。',
        action: '去稍后读',
      },
      {
        title: '建一条今天的任务',
        body: '按 N 新建，按 E 完成。今天 = 逾期和今日到期。',
        action: '去今天',
      },
      {
        title: '打开周报，钉上任务',
        body: '用 / 插入任务。随时按 ⌘K 跳转到列表、稍后读和报告。',
        action: '打开周报',
      },
    ],
  },
  checklist: {
    title: '开始使用',
    dismiss: '完成引导',
    remaining: '还差 {n} 项',
    items: {
      createdTask: '建一条任务',
      completedTask: '完成一条任务',
      capturedInbox: '保存一页稍后读',
      openedWeekly: '打开周报',
      pinnedTask: '把任务钉进报告',
    },
  },
  palette: {
    placeholder: '跳转到清单、任务、稍后读或报告',
    empty: '没有匹配的跳转。',
    goto: '跳转',
    list: '清单',
    task: '任务',
    inbox: '稍后读',
    report: '报告',
    board: '看板',
    calendar: '周视图',
  },
  search: {
    placeholder: '搜任务、稍后读和报告',
    loading: '搜索中…',
  },
  todos: {
    overdue: '已过期',
    pinned: '置顶',
    postpone: '顺延',
    postponeOverdue: '顺延到今天',
    views: { list: '列表', board: '看板', week: '日历' },
    priorityLabel: '优先级',
    notesPlaceholder: '输入内容',
    notesWysiwyg: '排版',
    notesSource: '源码',
    boardByStatus: '按状态',
    boardByPriority: '按优先级',
    status: { todo: '待办', doing: '进行中', done: '已完成', canceled: '已取消' },
    priority: { p0: 'P0', p1: 'P1', p2: 'P2', p3: 'P3' },
    quickAddPlaceholder: '添加任务',
    title: '标题',
    filterPlaceholder: '筛选当前列表',
    undoComplete: '已完成',
    undo: '撤销',
    retry: '重试',
    offline: '离线，仅可浏览',
    allDay: '全天',
    due: '截止',
    start: '开始',
    addDate: '添加日期',
    addTime: '添加时间',
    schedule: '日期与时间',
    datePoint: '日期',
    dateRange: '时间段',
    quickToday: '今天',
    quickTomorrow: '明天',
    quickWeek: '一周后',
    quickEvening: '今晚',
    startTime: '开始时间',
    endTime: '结束时间',
    confirmSchedule: '确定',
    clearSchedule: '清除',
    hideCompleted: '隐藏已完成',
    showCompleted: '显示已完成',
    hideDetail: '隐藏详情',
    viewMenu: '视图',
    composeTo: '添加任务至',
    composeWhat: '准备做什么？',
    composeIntent: '用一句话说要做的事，日期和优先级会自动填',
    interpreting: '正在理解…',
    add: '添加',
    clearDate: '清除日期',
    clearTime: '清除时间',
    dateDone: '完成',
    timePicker: '时间选择器',
    remindTime: '时间',
    openDetail: '打开',
    addOnDay: '添加到',
    notes: '备注',
    tags: '标签',
    addTag: '新标签',
    subtasks: '子任务',
    addSubtask: '添加子任务',
    list: '清单',
    recurrence: '重复',
    recurrenceNone: '不重复',
    recurrenceDaily: '每天',
    recurrenceWeekly: '每周',
    recurrenceMonthly: '每月',
    recurrenceYearly: '每年',
    recurrenceWeekdays: '工作日',
    recurrenceWeekends: '周末',
    recurrenceHolidays: '节假日',
    recurrenceLegalWorkdays: '法定工作日',
    remind: '提醒',
    reminderNone: '不提醒',
    reminderDue: '准时',
    reminder5m: '提前 5 分钟',
    reminder15m: '提前 15 分钟',
    reminder30m: '提前 30 分钟',
    reminder1h: '提前 1 小时',
    reminder1d: '提前 1 天',
    reminderCustom: '自定义时间',
    deleteTask: '删除任务',
    scheduleToday: '安排到今天',
    scheduleTomorrow: '安排到明天',
    moveTo: '移动到',
    closeDetail: '关闭详情',
    pickTask: '点一条待办，详情会开在右边。',
    newList: '新建清单',
    newListPlaceholder: '清单名称',
    complete: '完成',
    more: '更多',
    loading: '加载中',
    weekPrev: '上一周',
    weekNext: '下一周',
    weekThis: '本周',
    weekday: ['日', '一', '二', '三', '四', '五', '六'],
    circadian: {
      night: '夜色还在，先把最要紧的做掉。',
      morning: '白天开始，从今天下手。',
      afternoon: '午后推进，一件一件清。',
      evening: '夜色收好，把明天留清楚。',
    },
  },
  inbox: {
    kicker: '先收进来，再慢慢读。',
    pasteUrl: '粘贴链接',
    pastePlaceholder: 'https:// 或写下一句备忘',
    extract: '预览',
    extracting: '正在抓取…',
    save: '保存',
    saving: '保存中…',
    cancel: '取消',
    retry: '重试',
    failed: '抓取失败',
    preview: '抓取结果',
    unprocessed: '待处理任务',
    saves: '未读 / 失败',
    unread: '未读',
    favorite: '收藏',
    unfavorite: '取消收藏',
    archive: '归档',
    unarchive: '取消归档',
    archived: '已归档',
    convert: '转为任务',
    converted: '已转为任务',
    convertKeptUrl: '原文链接已写进任务备注。',
    addToReport: '加入报告',
    addToReportStub: '报告里稍后就能插入这条稍后读。',
    fontSize: '正文字号',
    font: { sm: '小', md: '中', lg: '大' },
    actions: '条目操作',
    originalUrl: '原文',
    copyLink: '复制链接',
    copied: '已复制',
    noOriginalUrl: '没有原文链接',
    noBody: '没有正文。',
    back: '返回列表',
    openTask: '查看任务',
    processing: '正在抓取',
    installHint: '扩展稍后从商店安装，现在可以先粘贴链接。',
    loading: '加载中',
    showArchived: '查看归档',
    hideArchived: '返回收藏',
    group: { today: '今天', yesterday: '昨天', week: '本周', earlier: '更早' },
    filters: { all: '全部', unread: '未读', favorite: '收藏', archived: '归档' },
    unit: '篇',
    filterEmpty: '这个筛选下没有条目。',
    source: {
      extension: '插件收藏',
      wechat: '微信收藏',
      web: '网页收藏',
      mobile: '手机收藏',
      manual: '手动',
    },
  },
  settings: {
    title: '设置',
    account: '账户',
    appearance: '外观',
    prefs: '偏好',
    tabs: {
      account: '账户',
      appearance: '外观',
      notifications: '通知',
      prefs: '偏好',
      llm: '模型',
    },
    llm: {
      title: '大模型',
      hint: '新建任务时用模型识别意图，自动填写日期、优先级和摘要。接口兼容 OpenAI Chat Completions。',
      apiBase: 'API Base',
      apiBaseHint: '例如 https://open.bigmodel.cn/api/paas/v4',
      apiKey: 'API Key',
      apiKeySet: '已保存。留空则不更改。',
      apiKeyPlaceholder: '不会回显已保存的密钥',
      model: '模型名称',
      modelHint: '例如 glm-4-flash',
      save: '保存',
      saved: '已保存',
      test: '测试连接',
      testOk: '连接正常',
      clearKey: '清除密钥',
      notConfigured: '还没有配置模型。配置后，新建任务会自动识别日期和优先级。',
    },
    displayName: '怎么称呼你',
    changeAvatar: '更换头像',
    avatarAlt: '头像',
    saveProfile: '保存资料',
    timezone: '时区',
    weekStartsOn: '一周从哪天开始',
    weekSun: '周日',
    weekMon: '周一',
    notify: {
      title: '通知',
      hint: '到点通过你配置的渠道推送。先接通 MeoW。',
      taskRemind: '有提醒时间时推送',
      taskDue: '没有提醒时按到期推送',
      allDayTime: '全天任务默认推送时刻',
      quiet: '免打扰',
      quietStart: '开始',
      quietEnd: '结束',
      quietOff: '关闭免打扰',
      channels: '渠道',
      meow: 'MeoW',
      nickname: 'MeoW 昵称',
      enabled: '启用',
      saveChannel: '保存渠道',
      test: '发送测试',
      testing: '发送中…',
      testOk: '测试已发出',
      lastError: '最近错误',
    },
  },
  boot: {
    label: '正在恢复会话',
  },
} as const;

export const HOME_PATH = '/todos/lists/smart:today';
