import { zhCN } from '@vital/tokens';

/** Web UI is zh-CN. Shared keys live in @vital/tokens; screen copy stays here until i18n grows. */
export const t = {
  brand: zhCN.brand,
  nav: {
    ...zhCN.nav,
    library: '资料库',
    logout: '退出登录',
    quickAdd: '新建',
  },
  lists: zhCN.lists,
  reports: zhCN.reports,
  rail: {
    rhythm: '节奏',
    capture: '收集',
    reflect: '复盘',
    lists: '列表',
  },
  theme: {
    label: '主题',
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
  },
  auth: {
    loginKicker: '夜色收好，白天接着做。',
    registerKicker: '先把一件事放进来。',
    loginTitle: '登录 Vital',
    registerTitle: '加入 Vital',
    email: '邮箱',
    password: '密码',
    displayName: '怎么称呼你',
    confirmPassword: '再输一遍密码',
    loginSubmit: '登录',
    registerSubmit: '注册',
    loggingIn: '登录中…',
    registering: '注册中…',
    noAccount: '还没有账号？',
    hasAccount: '已有账号？',
    passwordMismatch: '两次密码不一致',
    invalidEmail: '请输入正确的邮箱地址',
    passwordMin: '密码至少 8 位',
    passwordRequired: '请输入密码',
    displayNameRequired: '请输入名字',
  },
  empty: {
    today: '今天还没有安排，也没有逾期。按 N 新建。',
    inboxList: '收集箱是空的。',
    upcoming: '这里还没有任务。',
    done: '完成的任务会出现在这里。',
    userList: '把任务拖进来，或按 N。',
    board: '还没有卡片。',
    calendar: '这一周没有日期。',
    inbox: '把稍后读的页先丢进来。',
    inboxReader: '打开一条稍后再读。',
    reports: '写今天的日报，把完成的事留下痕迹。',
    reportEditor: '用 / 插入任务或稍后读。',
    search: '输入关键词搜任务、稍后读和报告。',
    library: '标签和模板会集中在这里。',
    settings: '主题、时区和账户都在这里。',
    onboarding: '先建一条任务，或把一页收进稍后读。',
    notFound: '没有这个页面。',
    tags: '还没有标签。',
    actionNew: '新建',
    actionExtension: '安装扩展',
    actionDaily: '打开今日日报',
    actionHome: '回到今天',
  },
  todos: {
    overdue: '逾期',
    views: { list: '列表', board: '看板', week: '周' },
    boardByStatus: '按状态',
    boardByPriority: '按优先级',
    status: { todo: '待办', doing: '进行中', done: '已完成', canceled: '已取消' },
    priority: { p0: 'P0', p1: 'P1', p2: 'P2', p3: 'P3' },
    quickAddPlaceholder: '添加任务',
    title: '标题',
    filterPlaceholder: '筛选当前列表',
    undoComplete: '已完成',
    undo: '撤销',
    retry: '重试',
    offline: '离线，仅可浏览',
    allDay: '全天',
    due: '截止',
    start: '开始',
    notes: '备注',
    tags: '标签',
    addTag: '新标签',
    subtasks: '子任务',
    addSubtask: '添加子任务',
    list: '列表',
    recurrence: '重复',
    recurrenceNone: '不重复',
    recurrenceDaily: '每天',
    recurrenceWeekly: '每周',
    recurrenceMonthly: '每月',
    recurrenceYearly: '每年',
    remind: '提醒',
    deleteTask: '删除任务',
    closeDetail: '关闭详情',
    newList: '新建列表',
    newListPlaceholder: '列表名称',
    timeBucket: '安排',
    complete: '完成',
    more: '更多',
    loading: '加载中',
    weekPrev: '上一周',
    weekNext: '下一周',
    weekThis: '本周',
    weekday: ['日', '一', '二', '三', '四', '五', '六'],
    circadian: {
      night: '夜色还在，先把最要紧的做掉。',
      morning: '白天开始，从今天下手。',
      afternoon: '午后推进，一件一件清。',
      evening: '夜色收好，把明天留清楚。',
    },
  },
  settings: {
    title: '设置',
    account: '账户',
    appearance: '外观',
  },
  boot: {
    label: '正在恢复会话',
  },
} as const;

export const HOME_PATH = '/todos/lists/smart:today';
