import { zhCN } from '@vital/tokens';

export const copy = {
  brand: zhCN.brand,
  nav: {
    ...zhCN.nav,
    today: zhCN.lists.today,
    library: '我的',
    me: '我的',
  },
  lists: zhCN.lists,
  reports: zhCN.reports,
  auth: {
    email: '邮箱',
    password: '密码',
    displayName: '昵称',
    login: '登录',
    register: '注册',
    loggingIn: '登录中…',
    registering: '注册中…',
    noAccount: '没有账号？注册',
    hasAccount: '已有账号？登录',
    logout: '退出登录',
    invalidLogin: '请输入有效的邮箱和密码',
    invalidRegister: '请填写昵称、有效邮箱和至少 8 位密码',
  },
  empty: {
    today: '今天还没有安排，也没有逾期。',
    inboxList: '收集箱是空的。',
    upcoming: '这里还没有任务。',
    done: '完成的任务会出现在这里。',
    userList: '把任务拖进来，或按新建。',
    inbox: '把稍后读的页先丢进来。',
    inboxReader: '打开一条稍后再读。',
    reports: '写今天的日报，把完成的事留下痕迹。',
    reportBody: '用 / 插入任务或稍后读。',
    search: '输入关键词搜任务、稍后读和报告。',
    searchNone: '没有匹配的任务、稍后读或报告。',
    tags: '还没有标签。',
  },
  onboarding: {
    skipAll: '跳过引导',
    next: '下一步',
    start: '开始使用',
    steps: [
      {
        title: '把一页收进来',
        body: '稍后读是口袋。粘贴链接，先把想读的页丢进来。',
        action: '去稍后读',
      },
      {
        title: '建一条今天的任务',
        body: '从今天下手。完成后可以撤销。',
        action: '去今天',
      },
      {
        title: '打开周报，钉上任务',
        body: '周报会留下这一周的痕迹。把完成的任务钉进去。',
        action: '打开报告',
      },
    ],
  },
  checklist: {
    title: '开始使用',
    dismiss: '完成引导',
    items: {
      createdTask: '建一条任务',
      completedTask: '完成一条任务',
      capturedInbox: '保存一页稍后读',
      openedWeekly: '打开周报',
      pinnedTask: '把任务钉进报告',
    },
  },
  actions: {
    create: '新建',
    retry: '重试',
    save: '保存',
    saving: '保存中…',
    convert: '转为任务',
    fill: '从本周期填充',
    undo: '撤销',
    completed: '已完成',
    insertTask: '插入任务',
    insertInbox: '插入稍后读',
    confirm: '确认保存',
    preview: '预览链接',
    openDaily: '打开今日日报',
    loadMore: '加载更多',
    archive: '归档',
    cancel: '取消',
    add: '添加',
  },
  fields: {
    title: '标题',
    url: '链接',
    notes: '备注',
    markdown: 'Markdown',
    search: '搜索',
  },
  status: {
    overdue: '逾期',
    dueToday: '今天到期',
    unread: '未读',
    later: '稍后再读',
    archived: '已归档',
    converted: '已转换',
  },
  priority: {
    0: 'P0',
    1: 'P1',
    2: 'P2',
    3: 'P3',
  },
  toast: {
    remoteUpdated: '远端已更新',
    saved: '已保存',
    converted: '已转为任务',
    revisionConflict: '报告已被更新，请先同步',
  },
  theme: {
    label: '主题',
    hint: '浅色、深色，或跟随系统。',
  },
  loading: '加载中',
  offline: '离线，仅可浏览',
  back: '返回',
  chipTask: '任务',
  chipInbox: '稍后读',
  deleted: '已删除',
} as const;
