[[permission]]
identifier = "allow-hide-main"
description = "Enables the hide_main command without any pre-configured scope."
commands.allow = ["hide_main"]

[[permission]]
identifier = "deny-hide-main"
description = "Denies the hide_main command without any pre-configured scope."
commands.deny = ["hide_main"]
