[[permission]]
identifier = "allow-set-badge"
description = "Enables the set_badge command without any pre-configured scope."
commands.allow = ["set_badge"]

[[permission]]
identifier = "deny-set-badge"
description = "Denies the set_badge command without any pre-configured scope."
commands.deny = ["set_badge"]
